name: brew pr-pull

on:
  workflow_dispatch:
    inputs:
      pr:
        description: Pull request number to publish bottles for
        required: true
        type: number

jobs:
  pr-pull:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: none
      pull-requests: write
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Bottle and publish
        env:
          PR: ${{ inputs.pr }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/bottle-and-publish.sh "$PR"
